variables:
- group: Oryx
- name: ascName
  value: oryx-new-service-connection
- name: acrName
  value: oryxdevmcr.azurecr.io
- name: skipComponentGovernanceDetection
  value: true
- name: Packaging.EnableSBOMSigning
  value: true

jobs:
- template: ../templates/_buildimageBasesJobTemplate.yml
  parameters:
    displayName: Build php bookworm runtime base images
    scriptPath: ./build/buildRunTimeImageBases.sh
    imageDir: php-fpm
    imageDebianFlavor: bookworm
    artifactsFileName: php-fpm-runtimeimage-bases-bookworm.txt
    jobName: Build_PHP_Fpm_Bookworm_Base

- job: Release_PhpRuntimeBaseImage
  dependsOn:
    - Build_PHP_Fpm_Bookworm_Base
  displayName: Push images to MCR
  timeoutInMinutes: 250
  pool:
    name: AzurePipelines-EO
    demands:
      - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
  steps:
    - template: ../templates/_releaseBaseImagesStepTemplate.yml
      parameters:
        baseImageName: 'php-fpm'
