parameters:
  - name: buildImages
    type: object
    default:
      - 
        imageTypeDisplay: Latest
        imageType: latest
        imageTypeTest: latest
      - 
        imageTypeDisplay: LtsVersions
        imageType: ltsversions
        imageTypeTest: ltsversions
      - 
        imageTypeDisplay: Jamstack
        imageType: jamstack
        imageTypeTest: jamstack
      - 
        imageTypeDisplay: GithubActions
        imageType: githubactions
        imageTypeTest: githubactions
      - 
        imageTypeDisplay: VsoFocal
        imageType: vso-focal
        imageTypeTest: vso-focal
      - 
        imageTypeDisplay: VsoFocal2
        imageType: vso-focal
        imageTypeTest: vso-focal-2
      - 
        imageTypeDisplay: Full
        imageType: full
        imageTypeTest: full
      - 
        imageTypeDisplay: Cli
        imageType: cli
        imageTypeTest: cli
      - 
        imageTypeDisplay: Buildpack
        imageType: buildpack
        imageTypeTest: buildpack

resources:
- repo: self
  fetchDepth: 15

variables:
  group: Oryx
  Packaging.EnableSBOMSigning: true

jobs:
- job: Job_Security
  displayName: Security
  pool:
    name: Azure Pipelines
    vmImage: windows-2022
  steps:
  - template: templates/_securityChecks.yml

- ${{ each buildImage in parameters.buildImages }}:
  - job: Job_BuildImage_${{ buildImage.imageTypeDisplay }}
    displayName: Build and Test Build ${{ buildImage.imageTypeDisplay }} Image
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
    timeoutInMinutes: 480
    steps:
    - script: |
        echo "##vso[task.setvariable variable=BuildBuildImages;]true"
        echo "##vso[task.setvariable variable=TestBuildImages;]true"
        echo "##vso[task.setvariable variable=PushBuildImages;]false"
        echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
        echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
        echo "##vso[task.setvariable variable=RELEASE_TAG_NAME;]$(Build.BuildNumber)"
      displayName: 'Set variables'
    - template: templates/_buildTemplate.yml
      parameters:
          imageType: ${{ buildImage.imageType }}
          imageTypeTest: ${{ buildImage.imageTypeTest }}

- job: Job_RuntimeImages
  displayName: Build and Test Runtime Images
  pool:
    name: AzurePipelines-EO
    demands:
      - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
  timeoutInMinutes: 480
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]true"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
      echo "##vso[task.setvariable variable=RELEASE_TAG_NAME;]$(Build.BuildNumber)"
    displayName: 'Set variables'
  - template: templates/_buildTemplate.yml

trigger: none