resources:
- repo: self
  fetchDepth: 15

variables:
  group: Oryx
  Packaging.EnableSBOMSigning: true

jobs:
- job: Job_Security
  displayName: Security
  pool:
    name: Azure Pipelines
    vmImage: windows-2022
  steps:
  - template: templates/_securityChecks.yml

#- job: Job_BuildImage_ltsVersions
#  displayName: Build and Test Build LtsVersions Image
#  pool:
#    name: AzurePipelines-EO
#    demands:
#      - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
#  timeoutInMinutes: 480
#  steps:
#  - script: |
#      echo "##vso[task.setvariable variable=BuildBuildImages;]true"
#      echo "##vso[task.setvariable variable=TestBuildImages;]true"
#      echo "##vso[task.setvariable variable=PushBuildImages;]false"
#      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
#      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
#      echo "##vso[task.setvariable variable=RELEASE_TAG_NAME;]$(Build.BuildNumber)"
#    displayName: 'Set variables'
#  - template: templates/_buildTemplate.yml
#    parameters:
#        imageType: ltsversions

#- job: Job_BuildImage_Jamstack
#  displayName: Build and Test Build Jamstack Image
#  pool:
#    name: AzurePipelines-EO
#    demands:
#      - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
#  timeoutInMinutes: 480
#  steps:
#  - script: |
#      echo "##vso[task.setvariable variable=BuildBuildImages;]true"
#      echo "##vso[task.setvariable variable=TestBuildImages;]true"
#      echo "##vso[task.setvariable variable=PushBuildImages;]false"
#      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
#      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
#      echo "##vso[task.setvariable variable=RELEASE_TAG_NAME;]$(Build.BuildNumber)"
#    displayName: 'Set variables'
#  - template: templates/_buildTemplate.yml
#    parameters:
#        imageType: jamstack

- job: Job_BuildImage_latest
  displayName: Build and Test Build Latest Image
  pool:
    name: AzurePipelines-EO
    demands:
      - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
  timeoutInMinutes: 480
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildBuildImages;]true"
      echo "##vso[task.setvariable variable=TestBuildImages;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
      echo "##vso[task.setvariable variable=RELEASE_TAG_NAME;]$(Build.BuildNumber)"
    displayName: 'Set variables'
  - template: templates/_buildTemplate.yml
    parameters:
        imageType: latest

- job: Job_RuntimeImages
  displayName: Build and Test Runtime Images
  pool:
    name: AzurePipelines-EO
    demands:
      - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
  timeoutInMinutes: 480
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]true"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
      echo "##vso[task.setvariable variable=RELEASE_TAG_NAME;]$(Build.BuildNumber)"
    displayName: 'Set variables'
  - template: templates/_buildTemplate.yml

trigger: none