name: Oryx-SDK-Runtime-Automation-Trigger

on:
  # Temporary for testing
  push:
    branches:
      - 'williamhe/**'
  # runs on 12:55 (5:55AM PST) & 23:55 UTC
  schedule:
    - cron:  '55 12,23 * * *'  
  workflow_call:
    inputs:
      releaseDate:
        required: false
        type: string
        default: 2022-12-13
      platformName:
        required: true
        type: string

jobs:
  ReuseableMatrixJobForDeployment:
    strategy:
      matrix:
        platformName: [dotnet]
    uses: ./.github/workflows/automationTemplate.yaml 
    with:
      platformName: ${{ matrix.platformName }}
    secrets: inherit