name: Caller

on:
  push:
    branches:
      - 'williamhe/**'
  # runs on 12:55 (5:55AM PST) & 23:55 UTC
  schedule:
    - cron:  '55 12,23 * * *'  

jobs:
  ReuseableMatrixJobForDeployment:
    strategy:
      matrix:
        platformName: [dotnet]
        platformNameCamelCase: [DotNetCore]
    uses: ./.github/workflows/main.yaml 
    with:
      platformName: ${{ matrix.platformName }}
      platformNameCamelCase: ${{ matrix.platformNameCamelCase }}
    secrets: inherit