name: "Auto Assign Issue"

on:
  issues:
    types: [opened, reopened]

jobs:
  Debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Assign issues
        run: |
          chmod +x ./oncall/autoIssueAssign.sh
          ./oncall/autoIssueAssign.sh ./oncall/customRotation.txt ${{ secrets.GITHUB_TOKEN }}