# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "williamhe/**" ]
  pull_request:
    branches: [ "williamhe/**" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup dotnet
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      # Runs a single command using the runners shell
      - name: Run SDK automation
        run: time dotnet run --project build/tools/Automation/Automation.csproj

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,  
          echo test, and deploy your project.

      - name: Run Generate Constants
        run: ./build/generateConstants.sh || true
      
      - name: Create commits
        run: |
          git status
          git config user.name 'William Hernandez'
          git config user.email 'williamhe@microsoft.com'
          git add build/*
          git add src/BuildScriptGenerator/*
          git commit -m "Add new version"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
     
      # Trigger Oryx pipeline
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://devdiv.visualstudio.com/DevDiv
          azure-pipeline-name: Oryx-PlatformBinary-DotNetCore
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}